package com.boot.module;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.uid
     *
     * @mbg.generated Mon Nov 06 15:27:02 CST 2017
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.emplyee_id
     *
     * @mbg.generated Mon Nov 06 15:27:02 CST 2017
     */
    private String emplyeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.gender
     *
     * @mbg.generated Mon Nov 06 15:27:02 CST 2017
     */
    private Integer gender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.uid
     *
     * @return the value of member.uid
     *
     * @mbg.generated Mon Nov 06 15:27:02 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.uid
     *
     * @param uid the value for member.uid
     *
     * @mbg.generated Mon Nov 06 15:27:02 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.emplyee_id
     *
     * @return the value of member.emplyee_id
     *
     * @mbg.generated Mon Nov 06 15:27:02 CST 2017
     */
    public String getEmplyeeId() {
        return emplyeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.emplyee_id
     *
     * @param emplyeeId the value for member.emplyee_id
     *
     * @mbg.generated Mon Nov 06 15:27:02 CST 2017
     */
    public void setEmplyeeId(String emplyeeId) {
        this.emplyeeId = emplyeeId == null ? null : emplyeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.gender
     *
     * @return the value of member.gender
     *
     * @mbg.generated Mon Nov 06 15:27:02 CST 2017
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.gender
     *
     * @param gender the value for member.gender
     *
     * @mbg.generated Mon Nov 06 15:27:02 CST 2017
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }
}