package com.boot.module;

public class TokenInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token_info.id
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token_info.create_time
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token_info.app_id
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token_info.token
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    private byte[] token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token_info.id
     *
     * @return the value of token_info.id
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token_info.id
     *
     * @param id the value for token_info.id
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token_info.create_time
     *
     * @return the value of token_info.create_time
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token_info.create_time
     *
     * @param createTime the value for token_info.create_time
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token_info.app_id
     *
     * @return the value of token_info.app_id
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token_info.app_id
     *
     * @param appId the value for token_info.app_id
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token_info.token
     *
     * @return the value of token_info.token
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public byte[] getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token_info.token
     *
     * @param token the value for token_info.token
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public void setToken(byte[] token) {
        this.token = token;
    }
}