package com.boot.module;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.app_id
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.request_count
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    private Integer requestCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.bind_ip
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    private String bindIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mark
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.app_secret
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    private byte[] appSecret;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.app_id
     *
     * @return the value of user_info.app_id
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.app_id
     *
     * @param appId the value for user_info.app_id
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.request_count
     *
     * @return the value of user_info.request_count
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public Integer getRequestCount() {
        return requestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.request_count
     *
     * @param requestCount the value for user_info.request_count
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public void setRequestCount(Integer requestCount) {
        this.requestCount = requestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.bind_ip
     *
     * @return the value of user_info.bind_ip
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public String getBindIp() {
        return bindIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.bind_ip
     *
     * @param bindIp the value for user_info.bind_ip
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public void setBindIp(String bindIp) {
        this.bindIp = bindIp == null ? null : bindIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mark
     *
     * @return the value of user_info.mark
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mark
     *
     * @param mark the value for user_info.mark
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.app_secret
     *
     * @return the value of user_info.app_secret
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public byte[] getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.app_secret
     *
     * @param appSecret the value for user_info.app_secret
     *
     * @mbg.generated Mon Nov 06 19:43:43 CST 2017
     */
    public void setAppSecret(byte[] appSecret) {
        this.appSecret = appSecret;
    }
}