spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
    #初始化数量
    initialSize: 1
    minIdle: 3
    #最大活跃数
    maxActive: 20
    #最大连接等待超时时间
    maxWait: 60000
    #打开pscache ,并且制定每个连接pscache 的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties 属性来打开 mergesql 功能 慢sql 记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /**
redis:
  host: 127.0.0.1
  port: 6379
  pool:
    max-idle: 20 #连接池中的最大空闲连接
    min-idle: 1 #连连接池中的最小空闲连接
    max-active: 20 #连接池最大连接数
    max-wait: 60000 #
  database: 0

logging:
  config: classpath:logback-spring.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启数据库与bean 驼峰命令约定，自动对应到实体类
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.boot.module
